
# Paw Control – Services

gps_start_walk:
  name: GPS-Tracking starten
  description: Startet einen Spaziergang für einen Hund.
  fields:
    dog_id:
      description: Hund-ID (optional; wenn leer, wird der erste Hund genutzt)
      example: rex
      required: false
      selector: { text: {} }
    walk_type:
      description: Typ des Spaziergangs (z. B. normal, auto_detected)
      required: false
      default: normal
      selector: { text: {} }

gps_end_walk:
  name: GPS-Tracking beenden
  description: Beendet den Spaziergang und berechnet Distanz/Dauer/Ø-Geschwindigkeit.
  fields:
    dog_id:
      required: false
      selector: { text: {} }
    rating:
      description: Bewertung 1–5 (optional)
      required: false
      selector: { number: { min: 1, max: 5, step: 1 } }
    notes:
      description: Notizen
      required: false
      selector: { text: {} }

gps_export_last_route:
  name: Letzte Route exportieren
  description: Exportiert die letzte Route als GeoJSON oder GPX.
  fields:
    dog_id:
      required: false
      selector: { text: {} }
    format:
      required: false
      default: geojson
      selector: { select: { options: [geojson, gpx] } }
    to_media:
      required: false
      default: false
      selector: { boolean: {} }

gps_generate_diagnostics:
  name: GPS-Diagnose erstellen
  description: Schreibt Diagnosedaten in /config/pawcontrol_diagnostics/
  fields:
    dog_id:
      required: false
      selector: { text: {} }

gps_reset_stats:
  name: GPS-Statistiken zurücksetzen
  description: Setzt diagnostische GPS-Zähler zurück.
  fields:
    dog_id:
      required: false
      selector: { text: {} }

gps_pause_tracking:
  name: GPS-Tracking pausieren
  description: Pausiert das Tracking (sofern Handler aktiv).
  fields:
    dog_id:
      required: false
      selector: { text: {} }

gps_resume_tracking:
  name: GPS-Tracking fortsetzen
  description: Setzt das Tracking fort (sofern Handler aktiv).
  fields:
    dog_id:
      required: false
      selector: { text: {} }

toggle_geofence_alerts:
  name: Geofence-Alerts umschalten
  description: Aktiviert/Deaktiviert Benachrichtigungen bei Verlassen/Betreten der Zone.
  fields:
    dog_id:
      required: false
      selector: { text: {} }
    enable:
      required: true
      selector: { boolean: {} }

export_options:
  name: Optionen exportieren
  description: Schreibt die aktuellen Options (Config-Entry) als JSON nach /config/pawcontrol_options_export.json
  fields: {}

import_options:
  name: Optionen importieren
  description: Lädt JSON-Optionen von Pfad (Standard /config/pawcontrol_options_export.json) in die Config-Entry
  fields:
    path:
      required: false
      selector: { text: {} }

send_medication_reminder:
  name: Medikationserinnerung senden
  description: Versendet pro Slot eine Erinnerung (oder auf Basis der Zuordnung je Mahlzeit).
  fields:
    dog_id: { required: true, selector: { text: {} } }
    meal: { required: false, selector: { select: { options: [breakfast, lunch, dinner] } } }
    slot: { required: false, selector: { number: { min: 1, max: 3, step: 1 } } }
    notes: { required: false, selector: { text: {} } }

route_history_list:
  name: Routenindex erzeugen
  description: Schreibt eine kompakte Index-Datei mit den letzten Routen nach /config/pawcontrol_diagnostics/
  fields:
    dog_id: { required: false, selector: { text: {} } }

route_history_purge:
  name: Routenverlauf bereinigen
  description: Löscht Routen, die älter sind als X Tage (wenn gesetzt).
  fields:
    older_than_days: { required: false, selector: { number: { min: 1, max: 3650, step: 1 } } }

route_history_export_range:
  name: Routenbereich exportieren
  description: Exportiert eine Sammlung von Routen (ohne Punkte) als ZIP ins Medienverzeichnis.
  fields:
    dog_id: { required: false, selector: { text: {} } }
    start: { required: false, selector: { text: {} } }
    end: { required: false, selector: { text: {} } }
    format: { required: false, default: geojson, selector: { select: { options: [geojson, gpx] } } }

purge_all_storage:
  name: Alle gespeicherten Daten löschen
  description: Löscht gespeicherte GPS-Einstellungen und den Routenverlauf (Storage).
  fields: {}


gps_list_webhooks:
  name: Webhooks auflisten
  description: Schreibt eine Datei mit allen Webhook-URLs in /config/pawcontrol_diagnostics/webhooks.json
  fields: {}


gps_regenerate_webhooks:
  name: Webhooks erneuern
  description: Erzeugt neue Webhook-IDs pro Hund und registriert sie.
  fields: {}


gps_post_location:
  name: GPS-Position posten (manuell)
  description: Manuelles Einspeisen einer GPS-Position (falls kein Webhook genutzt wird).
  fields:
    dog_id: { required: false, selector: { text: {} } }
    latitude: { required: true, selector: { number: { min: -90, max: 90, step: 0.000001 } } }
    longitude: { required: true, selector: { number: { min: -180, max: 180, step: 0.000001 } } }
    accuracy: { required: false, selector: { number: { min: 0, max: 1000, step: 0.1 } } }


notify_test:
  name: Test-Benachrichtigung senden
  description: Sendet eine Test-Nachricht über das konfigurierte Notify-Ziel (Fallback persistent_notification).
  fields: {}

