SERVICE_DAILY_RESET:
  description: Service 'SERVICE_DAILY_RESET' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Daily Reset
SERVICE_EMERGENCY_MODE:
  description: Service 'SERVICE_EMERGENCY_MODE' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Emergency Mode
SERVICE_END_WALK:
  description: Service 'SERVICE_END_WALK' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service End Walk
SERVICE_EXPORT_DATA:
  description: Service 'SERVICE_EXPORT_DATA' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Export Data
SERVICE_FEED_DOG:
  description: Service 'SERVICE_FEED_DOG' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Feed Dog
SERVICE_GENERATE_REPORT:
  description: Service 'SERVICE_GENERATE_REPORT' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Generate Report
SERVICE_LOG_HEALTH:
  description: Service 'SERVICE_LOG_HEALTH' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Log Health
SERVICE_LOG_MEDICATION:
  description: Service 'SERVICE_LOG_MEDICATION' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Log Medication
SERVICE_PLAY_WITH_DOG:
  description: Service 'SERVICE_PLAY_WITH_DOG' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Play With Dog
SERVICE_START_GROOMING:
  description: Service 'SERVICE_START_GROOMING' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Start Grooming
SERVICE_START_TRAINING:
  description: Service 'SERVICE_START_TRAINING' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Start Training
SERVICE_START_WALK:
  description: Service 'SERVICE_START_WALK' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Start Walk
SERVICE_SYNC_SETUP:
  description: Service 'SERVICE_SYNC_SETUP' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Sync Setup
SERVICE_TOGGLE_VISITOR:
  description: Service 'SERVICE_TOGGLE_VISITOR' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Toggle Visitor
SERVICE_WALK_DOG:
  description: Service 'SERVICE_WALK_DOG' for Paw Control.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Service Walk Dog
gps_end_walk:
  description: Beendet den Spaziergang und berechnet Distanz/Dauer/Ø-Geschwindigkeit.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
    notes:
      description: Notizen
      required: false
      selector:
        text: {}
    rating:
      description: Bewertung 1–5 (optional)
      required: false
      selector:
        number:
          max: 5
          min: 1
          step: 1
  name: GPS-Tracking beenden
gps_export_last_route:
  description: Exportiert die letzte Route als GeoJSON oder GPX.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
    format:
      default: geojson
      required: false
      selector:
        select:
          options:
          - geojson
          - gpx
    to_media:
      default: false
      required: false
      selector:
        boolean: {}
  name: Letzte Route exportieren
gps_generate_diagnostics:
  description: Schreibt Diagnosedaten in /config/pawcontrol_diagnostics/
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
  name: GPS-Diagnose erstellen
gps_pause_tracking:
  description: Pausiert das Tracking (sofern Handler aktiv).
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
  name: GPS-Tracking pausieren
gps_post_location:
  description: Manuelles Einspeisen einer GPS-Position (falls kein Webhook genutzt
    wird).
  fields:
    accuracy:
      required: false
      selector:
        number:
          max: 1000
          min: 0
          step: 0.1
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
    latitude:
      required: true
      selector:
        number:
          max: 90
          min: -90
          step: 1.0e-06
    longitude:
      required: true
      selector:
        number:
          max: 180
          min: -180
          step: 1.0e-06
  name: GPS-Position posten (manuell)
gps_reset_stats:
  description: Setzt diagnostische GPS-Zähler zurück.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
  name: GPS-Statistiken zurücksetzen
gps_resume_tracking:
  description: Setzt das Tracking fort (sofern Handler aktiv).
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
  name: GPS-Tracking fortsetzen
gps_start_walk:
  description: Startet einen Spaziergang für einen Hund.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      description: Hund-ID (optional; wenn leer, wird der erste Hund genutzt)
      example: rex
      required: false
      selector:
        text: {}
    walk_type:
      default: normal
      description: Typ des Spaziergangs (z. B. normal, auto_detected)
      required: false
      selector:
        text: {}
  name: GPS-Tracking starten
notify_test:
  description: Sendet eine Test-Nachricht über das konfigurierte Notify-Ziel (Fallback
    persistent_notification).
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Test-Benachrichtigung senden
purge_all_storage:
  description: Löscht gespeicherte GPS-Einstellungen und den Routenverlauf (Storage).
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
  name: Alle gespeicherten Daten löschen
route_history_export_range:
  description: Exportiert eine Sammlung von Routen (ohne Punkte) als ZIP ins Medienverzeichnis.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
    end:
      required: false
      selector:
        text: {}
    format:
      default: geojson
      required: false
      selector:
        select:
          options:
          - geojson
          - gpx
    start:
      required: false
      selector:
        text: {}
  name: Routenbereich exportieren
route_history_list:
  description: Schreibt eine kompakte Index-Datei mit den letzten Routen nach /config/pawcontrol_diagnostics/
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
  name: Routenindex erzeugen
route_history_purge:
  description: Löscht Routen, die älter sind als X Tage (wenn gesetzt).
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    older_than_days:
      required: false
      selector:
        number:
          max: 3650
          min: 1
          step: 1
  name: Routenverlauf bereinigen
toggle_geofence_alerts:
  description: Aktiviert/Deaktiviert Benachrichtigungen bei Verlassen/Betreten der
    Zone.
  fields:
    config_entry_id:
      description: Optional config entry ID to target a specific instance.
      example: abcd1234efgh5678
    dog_id:
      required: false
      selector:
        text: {}
    enable:
      required: true
      selector:
        boolean: {}
  name: Geofence-Alerts umschalten


prune_stale_devices:
  name: Prune stale devices
  description: Remove devices that are no longer present in the backend account.
  target:
    device:
      integration: pawcontrol
  fields:
    auto:
      name: Auto remove
      description: If true, remove immediately; otherwise only create a Repairs issue.
      required: false
      default: true
      selector:
        boolean:
