# Paw Control Services

start_walk:
  name: Start Walk
  description: Start tracking a walk for a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    source:
      name: Source
      description: How the walk was initiated
      required: false
      default: "manual"
      example: "manual"
      selector:
        select:
          options:
            - "manual"
            - "gps"
            - "door"

end_walk:
  name: End Walk
  description: End tracking a walk for a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    reason:
      name: Reason
      description: Why the walk ended
      required: false
      default: "manual"
      example: "manual"
      selector:
        select:
          options:
            - "manual"
            - "home"
            - "idle"

walk_dog:
  name: Quick Walk Log
  description: Log a completed walk with duration and distance
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    duration_min:
      name: Duration
      description: Walk duration in minutes
      required: true
      default: 30
      example: 30
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: "min"
    distance_m:
      name: Distance
      description: Walk distance in meters
      required: false
      default: 1000
      example: 1000
      selector:
        number:
          min: 1
          max: 100000
          step: 10
          unit_of_measurement: "m"

feed_dog:
  name: Feed Dog
  description: Record feeding for a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    meal_type:
      name: Meal Type
      description: Type of meal
      required: true
      default: "dinner"
      example: "dinner"
      selector:
        select:
          options:
            - "breakfast"
            - "lunch"
            - "dinner"
            - "snack"
    portion_g:
      name: Portion Size
      description: Portion size in grams
      required: false
      default: 200
      example: 200
      selector:
        number:
          min: 10
          max: 1500
          step: 10
          unit_of_measurement: "g"
    food_type:
      name: Food Type
      description: Type of food
      required: false
      default: "dry"
      example: "dry"
      selector:
        select:
          options:
            - "dry"
            - "wet"
            - "barf"
            - "treat"

log_health_data:
  name: Log Health Data
  description: Record health data for a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    weight_kg:
      name: Weight
      description: Dog weight in kilograms
      required: false
      example: 25.5
      selector:
        number:
          min: 0.5
          max: 100
          step: 0.1
          unit_of_measurement: "kg"
    note:
      name: Note
      description: Health note or observation
      required: false
      example: "Good appetite, active"
      selector:
        text:

log_medication:
  name: Log Medication
  description: Record medication given to a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    medication_name:
      name: Medication Name
      description: Name of the medication
      required: true
      example: "Heartguard"
      selector:
        text:
    dose:
      name: Dose
      description: Medication dose
      required: true
      example: "1 tablet"
      selector:
        text:

start_grooming_session:
  name: Start Grooming Session
  description: Log a grooming session for a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    type:
      name: Grooming Type
      description: Type of grooming
      required: true
      default: "brush"
      example: "brush"
      selector:
        select:
          options:
            - "bath"
            - "brush"
            - "trim"
            - "nails"
            - "ears"
            - "teeth"
            - "eyes"
    notes:
      name: Notes
      description: Grooming notes
      required: false
      example: "Full bath with shampoo"
      selector:
        text:

play_with_dog:
  name: Play Session
  description: Log a play session with a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    duration_min:
      name: Duration
      description: Play duration in minutes
      required: true
      default: 15
      example: 15
      selector:
        number:
          min: 1
          max: 240
          step: 1
          unit_of_measurement: "min"
    intensity:
      name: Intensity
      description: Play intensity level
      required: false
      default: "medium"
      example: "medium"
      selector:
        select:
          options:
            - "low"
            - "medium"
            - "high"

start_training_session:
  name: Start Training Session
  description: Log a training session with a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    topic:
      name: Training Topic
      description: What was trained
      required: true
      example: "Basic Commands"
      selector:
        text:
    duration_min:
      name: Duration
      description: Training duration in minutes
      required: false
      default: 15
      example: 15
      selector:
        number:
          min: 1
          max: 240
          step: 1
          unit_of_measurement: "min"
    notes:
      name: Notes
      description: Training notes
      required: false
      example: "Good progress on sit and stay"
      selector:
        text:

toggle_visitor_mode:
  name: Toggle Visitor Mode
  description: Enable or disable visitor mode
  fields:
    enabled:
      name: Enabled
      description: Whether visitor mode should be enabled
      required: true
      example: true
      selector:
        boolean:

activate_emergency_mode:
  name: Activate Emergency Mode
  description: Activate emergency mode with specified level
  fields:
    level:
      name: Level
      description: Emergency level
      required: false
      default: "info"
      example: "critical"
      selector:
        select:
          options:
            - "info"
            - "warn"
            - "critical"
    note:
      name: Note
      description: Emergency note
      required: false
      example: "Dog escaped"
      selector:
        text:

daily_reset:
  name: Daily Reset
  description: Reset all daily counters
  fields: {}

generate_report:
  name: Generate Report
  description: Generate activity report
  fields:
    scope:
      name: Scope
      description: Report scope
      required: false
      default: "daily"
      example: "daily"
      selector:
        select:
          options:
            - "daily"
            - "weekly"
            - "custom"
    target:
      name: Target
      description: Where to send the report
      required: false
      default: "notification"
      example: "notification"
      selector:
        select:
          options:
            - "file"
            - "notification"
    format:
      name: Format
      description: Report format
      required: false
      default: "text"
      example: "text"
      selector:
        select:
          options:
            - "text"
            - "csv"
            - "json"
            - "pdf"

export_health_data:
  name: Export Health Data
  description: Export health data for a dog
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog
      required: true
      example: "rex"
      selector:
        text:
    from:
      name: From Date
      description: Start date for export
      required: false
      selector:
        date:
    to:
      name: To Date
      description: End date for export
      required: false
      selector:
        date:
    format:
      name: Format
      description: Export format
      required: false
      default: "csv"
      example: "csv"
      selector:
        select:
          options:
            - "csv"
            - "json"

sync_setup:
  name: Sync Setup
  description: Synchronize helpers and entities with current configuration
  fields: {}

notify_test:
  name: Test Notification
  description: Send a test notification
  fields:
    dog_id:
      name: Dog ID
      description: Identifier of the dog (optional)
      required: false
      example: "rex"
      selector:
        text:
    message:
      name: Message
      description: Test message to send
      required: false
      default: "Paw Control test notification"
      example: "Test notification for Rex"
      selector:
        text:
