feed_dog:
  description: Füttert den Hund und aktualisiert die Fütterungsstatistiken.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:

    meal_type:
      description: Art der Mahlzeit
      example: "morning"
      default: "morning"
      selector:
        select:
          options:
            - "morning"
            - "lunch"
            - "evening"
            - "snack"
    amount:
      description: Futtermenge in Gramm
      example: 200
      default: 100
      selector:
        number:
          min: 10
          max: 1000
          step: 10
          unit_of_measurement: "g"

start_walk:
  description: Startet einen neuen Spaziergang.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    walk_type:
      description: Art des Spaziergangs
      example: "normal"
      default: "normal"
      selector:
        select:
          options:
            - "short"
            - "normal"
            - "long"

end_walk:
  description: Beendet den aktuellen Spaziergang.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    duration:
      description: Dauer des Spaziergangs in Minuten
      example: 30
      default: 30
      selector:
        number:
          min: 1
          max: 300
          step: 1
          unit_of_measurement: "min"

update_gps:
  description: Aktualisiert die GPS-Position des Hundes.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    latitude:
      description: GPS Breitengrad
      example: 52.233333
      required: true
      selector:
        number:
          min: -90
          max: 90
          step: 0.000001
    longitude:
      description: GPS Längengrad
      example: 8.966667
      required: true
      selector:
        number:
          min: -180
          max: 180
          step: 0.000001
    accuracy:
      description: GPS Genauigkeit in Metern
      example: 10
      default: 10
      selector:
        number:
          min: 1
          max: 1000
          step: 1
          unit_of_measurement: "m"

health_check:
  description: Führt einen Gesundheitscheck durch.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    temperature:
      description: Körpertemperatur in °C
      example: 38.5
      selector:
        number:
          min: 35.0
          max: 42.0
          step: 0.1
          unit_of_measurement: "°C"
    weight:
      description: Aktuelles Gewicht in kg
      example: 25.5
      selector:
        number:
          min: 0.5
          max: 100.0
          step: 0.1
          unit_of_measurement: "kg"
    notes:
      description: Gesundheitsnotizen
      example: "Allgemein guter Zustand"
      selector:
        text:
          multiline: true

daily_reset:
  description: Setzt alle täglichen Daten zurück.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
