change_entity_profile:
  name: Change Entity Profile
  description: Change the entity profile to optimize performance and entity count
  target:
    integration: pawcontrol
  fields:
    profile:
      name: Entity Profile
      description: The profile to switch to (basic, standard, advanced, gps_focus, health_focus)
      required: true
      selector:
        select:
          options:
            - basic
            - standard
            - advanced
            - gps_focus
            - health_focus
    apply_immediately:
      name: Apply Immediately
      description: Apply changes immediately (requires reload) or wait for next restart
      default: false
      selector:
        boolean:

get_profile_info:
  name: Get Profile Information
  description: Get information about available entity profiles and current configuration
  target:
    integration: pawcontrol
  fields:
    include_estimates:
      name: Include Estimates
      description: Include entity count estimates for each profile
      default: true
      selector:
        boolean:

# Core Dog Management Services
add_dog:
  name: Add Dog
  description: Add a new dog to the Paw Control integration
  target:
    integration: pawcontrol
  fields:
    dog_name:
      name: Dog Name
      description: Name of the dog
      required: true
      example: "Buddy"
      selector:
        text:
    dog_breed:
      name: Breed
      description: Breed of the dog
      example: "Labrador Retriever"
      selector:
        text:
    dog_age:
      name: Age
      description: Age of the dog in years
      example: 3
      selector:
        number:
          min: 0
          max: 30
          mode: box
    dog_weight:
      name: Weight
      description: Weight of the dog in kg
      example: 25.5
      selector:
        number:
          min: 0.1
          max: 200
          step: 0.1
          mode: box
          unit_of_measurement: kg
    dog_size:
      name: Size Category
      description: Size category of the dog
      default: medium
      selector:
        select:
          options:
            - toy
            - small
            - medium
            - large
            - giant
    profile:
      name: Entity Profile
      description: Entity profile for this dog (inherits global if not set)
      selector:
        select:
          options:
            - default
            - basic
            - standard
            - advanced
            - gps_focus
            - health_focus

remove_dog:
  name: Remove Dog
  description: Remove a dog from the Paw Control integration
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog to remove
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor

update_dog:
  name: Update Dog Information
  description: Update information for an existing dog
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog to update
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    dog_name:
      name: Dog Name
      description: New name for the dog
      selector:
        text:
    dog_breed:
      name: Breed
      description: Updated breed
      selector:
        text:
    dog_age:
      name: Age
      description: Updated age in years
      selector:
        number:
          min: 0
          max: 30
          mode: box
    dog_weight:
      name: Weight
      description: Updated weight in kg
      selector:
        number:
          min: 0.1
          max: 200
          step: 0.1
          mode: box
          unit_of_measurement: kg
    dog_size:
      name: Size Category
      description: Updated size category
      selector:
        select:
          options:
            - toy
            - small
            - medium
            - large
            - giant

# Feeding Management
log_feeding:
  name: Log Feeding
  description: Record a feeding event for a dog
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog that was fed
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    meal_type:
      name: Meal Type
      description: Type of meal
      default: regular
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
            - snack
            - treat
            - regular
    food_amount:
      name: Food Amount
      description: Amount of food in grams
      example: 250
      selector:
        number:
          min: 0
          max: 2000
          step: 10
          mode: box
          unit_of_measurement: g
    food_type:
      name: Food Type
      description: Type of food given
      default: dry
      selector:
        select:
          options:
            - dry
            - wet
            - raw
            - mixed
            - homemade
    notes:
      name: Notes
      description: Additional notes about the feeding
      selector:
        text:
          multiline: true

skip_meal:
  name: Skip Meal
  description: Record that a scheduled meal was skipped
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    meal_type:
      name: Meal Type
      description: Which meal was skipped
      required: true
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
    reason:
      name: Reason
      description: Reason for skipping the meal
      selector:
        text:

# Walk Management
start_walk:
  name: Start Walk
  description: Start tracking a walk for a dog
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog going for a walk
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    walk_type:
      name: Walk Type
      description: Type of walk
      default: regular
      selector:
        select:
          options:
            - quick
            - regular
            - long
            - play
            - training
    location:
      name: Location
      description: Starting location or area
      selector:
        text:
    with_person:
      name: With Person
      description: Person walking the dog
      selector:
        entity:
          domain: person

end_walk:
  name: End Walk
  description: End the current walk tracking
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    distance:
      name: Distance
      description: Distance walked in meters (auto-calculated if GPS enabled)
      selector:
        number:
          min: 0
          max: 50000
          step: 100
          mode: box
          unit_of_measurement: m
    rating:
      name: Walk Rating
      description: Rate the walk quality (1-5 stars)
      selector:
        number:
          min: 1
          max: 5
          mode: slider
    notes:
      name: Notes
      description: Notes about the walk
      selector:
        text:
          multiline: true

# Health Management
log_weight:
  name: Log Weight
  description: Record the dog's current weight
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    weight:
      name: Weight
      description: Current weight in kg
      required: true
      selector:
        number:
          min: 0.1
          max: 200
          step: 0.1
          mode: box
          unit_of_measurement: kg
    body_condition_score:
      name: Body Condition Score
      description: BCS rating (1-9 scale)
      selector:
        number:
          min: 1
          max: 9
          mode: slider

log_health_event:
  name: Log Health Event
  description: Record a health-related event or observation
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    event_type:
      name: Event Type
      description: Type of health event
      required: true
      selector:
        select:
          options:
            - symptom
            - medication
            - vaccination
            - vet_visit
            - grooming
            - dental
            - injury
            - recovery
    description:
      name: Description
      description: Detailed description of the event
      required: true
      selector:
        text:
          multiline: true
    severity:
      name: Severity
      description: Severity level (if applicable)
      selector:
        select:
          options:
            - minor
            - moderate
            - severe
            - critical

give_medication:
  name: Give Medication
  description: Record medication administration
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    medication_name:
      name: Medication Name
      description: Name of the medication
      required: true
      selector:
        text:
    dosage:
      name: Dosage
      description: Dosage given
      required: true
      selector:
        text:
    next_dose_time:
      name: Next Dose Time
      description: When the next dose is due
      selector:
        datetime:

# GPS & Location Services
set_geofence:
  name: Set Geofence
  description: Create or update a geofence zone for a dog
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    zone_name:
      name: Zone Name
      description: Name of the geofence zone
      required: true
      selector:
        text:
    latitude:
      name: Latitude
      description: Center latitude of the zone
      required: true
      selector:
        number:
          min: -90
          max: 90
          step: 0.000001
          mode: box
    longitude:
      name: Longitude
      description: Center longitude of the zone
      required: true
      selector:
        number:
          min: -180
          max: 180
          step: 0.000001
          mode: box
    radius:
      name: Radius
      description: Radius of the zone in meters
      default: 100
      selector:
        number:
          min: 10
          max: 5000
          step: 10
          mode: box
          unit_of_measurement: m
    alert_on_enter:
      name: Alert on Enter
      description: Send notification when dog enters zone
      default: true
      selector:
        boolean:
    alert_on_exit:
      name: Alert on Exit
      description: Send notification when dog exits zone
      default: true
      selector:
        boolean:

# Notification Services
send_reminder:
  name: Send Reminder
  description: Send a custom reminder notification
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog (optional for general reminders)
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    reminder_type:
      name: Reminder Type
      description: Type of reminder
      required: true
      selector:
        select:
          options:
            - feeding
            - walk
            - medication
            - vet_appointment
            - grooming
            - training
            - custom
    message:
      name: Message
      description: Custom reminder message
      required: true
      selector:
        text:
          multiline: true
    priority:
      name: Priority
      description: Notification priority
      default: normal
      selector:
        select:
          options:
            - low
            - normal
            - high
            - urgent

# Dashboard Management
refresh_dashboard:
  name: Refresh Dashboard
  description: Force refresh of the Paw Control dashboard
  target:
    integration: pawcontrol
  fields:
    regenerate:
      name: Regenerate
      description: Completely regenerate the dashboard (slower)
      default: false
      selector:
        boolean:

# Data Management
export_data:
  name: Export Data
  description: Export Paw Control data for backup or analysis
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: Specific dog to export (all if not specified)
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    data_types:
      name: Data Types
      description: Types of data to export
      default: ["all"]
      selector:
        select:
          multiple: true
          options:
            - all
            - feeding
            - walks
            - health
            - weight
            - medications
            - gps_history
    format:
      name: Export Format
      description: Format for the export
      default: json
      selector:
        select:
          options:
            - json
            - csv
            - yaml
    date_from:
      name: Date From
      description: Start date for export
      selector:
        date:
    date_to:
      name: Date To
      description: End date for export
      selector:
        date:

import_data:
  name: Import Data
  description: Import data from a backup or external source
  target:
    integration: pawcontrol
  fields:
    file_path:
      name: File Path
      description: Path to the import file
      required: true
      selector:
        text:
    merge_mode:
      name: Merge Mode
      description: How to handle existing data
      default: merge
      selector:
        select:
          options:
            - replace
            - merge
            - skip_existing

# Reset Services
reset_daily_counters:
  name: Reset Daily Counters
  description: Manually reset daily counters and statistics
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: Specific dog to reset (all if not specified)
      selector:
        entity:
          integration: pawcontrol
          domain: sensor

clear_history:
  name: Clear History
  description: Clear historical data for a dog
  target:
    integration: pawcontrol
  fields:
    dog_id:
      name: Dog ID
      description: ID of the dog
      required: true
      selector:
        entity:
          integration: pawcontrol
          domain: sensor
    data_type:
      name: Data Type
      description: Type of data to clear
      required: true
      selector:
        select:
          options:
            - all
            - feeding
            - walks
            - health
            - weight
            - medications
            - gps_history
    confirm:
      name: Confirm
      description: Confirm the action (must be true)
      required: true
      selector:
        boolean:
