# PawControl Services

feed_dog:
  name: Hund füttern
  description: Markiert eine Fütterung für den Hund
  fields:
    dog_name:
      name: Hundename
      description: Name des zu fütternden Hundes
      required: true
      example: "Max"
      selector:
        text:
    meal_type:
      name: Mahlzeit-Typ
      description: Art der Mahlzeit (auto = automatisch basierend auf Uhrzeit)
      required: false
      default: "auto"
      example: "breakfast"
      selector:
        select:
          options:
            - "auto"
            - "breakfast"
            - "lunch"
            - "dinner"
            - "snack"
    amount:
      name: Menge
      description: Futtermenge in Gramm
      required: false
      example: 200
      selector:
        number:
          min: 10
          max: 1000
          step: 10
          unit_of_measurement: "g"
    food_type:
      name: Futterart
      description: Art des Futters
      required: false
      example: "Trockenfutter"
      selector:
        text:
    notes:
      name: Notizen
      description: Zusätzliche Notizen zur Fütterung
      required: false
      example: "Hat gut gegessen"
      selector:
        text:
          multiline: true

start_walk:
  name: Spaziergang starten
  description: Startet einen Spaziergang mit dem Hund
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    walk_type:
      name: Spaziergang-Typ
      description: Art des Spaziergangs
      required: false
      default: "Normal"
      example: "Lang"
      selector:
        select:
          options:
            - "Kurz"
            - "Normal"
            - "Lang"
            - "Training"
            - "Freilauf"
    location:
      name: Ort
      description: Ort des Spaziergangs
      required: false
      example: "Park"
      selector:
        text:
    with_gps:
      name: Mit GPS
      description: GPS-Tracking aktivieren
      required: false
      default: false
      selector:
        boolean:

end_walk:
  name: Spaziergang beenden
  description: Beendet einen laufenden Spaziergang
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    duration:
      name: Dauer
      description: Dauer des Spaziergangs in Minuten
      required: true
      example: 30
      selector:
        number:
          min: 1
          max: 480
          step: 1
          unit_of_measurement: "min"
    distance:
      name: Distanz
      description: Zurückgelegte Distanz in Kilometern
      required: false
      example: 2.5
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: "km"
    rating:
      name: Bewertung
      description: Bewertung des Spaziergangs (1-5 Sterne)
      required: false
      example: 5
      selector:
        number:
          min: 1
          max: 5
          step: 1
    notes:
      name: Notizen
      description: Notizen zum Spaziergang
      required: false
      example: "Hat andere Hunde getroffen"
      selector:
        text:
          multiline: true
    route:
      name: Route
      description: GPS-Route als Liste von Koordinaten
      required: false
      advanced: true
      selector:
        object:

log_health:
  name: Gesundheitsdaten erfassen
  description: Erfasst Gesundheitsdaten des Hundes
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    weight:
      name: Gewicht
      description: Aktuelles Gewicht in kg
      required: false
      example: 25.5
      selector:
        number:
          min: 0.5
          max: 100
          step: 0.1
          unit_of_measurement: "kg"
    temperature:
      name: Temperatur
      description: Körpertemperatur in °C
      required: false
      example: 38.5
      selector:
        number:
          min: 35
          max: 42
          step: 0.1
          unit_of_measurement: "°C"
    symptoms:
      name: Symptome
      description: Beobachtete Symptome (kommagetrennt)
      required: false
      example: "Müdigkeit, Appetitlosigkeit"
      selector:
        text:
    energy_level:
      name: Energielevel
      description: Aktuelles Energielevel
      required: false
      default: "Normal"
      selector:
        select:
          options:
            - "Sehr niedrig"
            - "Niedrig"
            - "Normal"
            - "Hoch"
            - "Sehr hoch"
    notes:
      name: Notizen
      description: Zusätzliche Gesundheitsnotizen
      required: false
      selector:
        text:
          multiline: true

update_gps:
  name: GPS aktualisieren
  description: Aktualisiert die GPS-Position des Hundes
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    latitude:
      name: Breitengrad
      description: GPS-Breitengrad
      required: true
      example: 52.5200
      selector:
        number:
          min: -90
          max: 90
          step: 0.0001
    longitude:
      name: Längengrad
      description: GPS-Längengrad
      required: true
      example: 13.4050
      selector:
        number:
          min: -180
          max: 180
          step: 0.0001
    accuracy:
      name: Genauigkeit
      description: GPS-Genauigkeit in Metern
      required: false
      example: 10
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: "m"
    source:
      name: Quelle
      description: Quelle der GPS-Daten
      required: false
      example: "Smartphone"
      selector:
        text:

set_mood:
  name: Stimmung setzen
  description: Setzt die aktuelle Stimmung des Hundes
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    mood:
      name: Stimmung
      description: Aktuelle Stimmung
      required: true
      example: "😊 Fröhlich"
      selector:
        select:
          options:
            - "😊 Fröhlich"
            - "😐 Neutral"
            - "😟 Traurig"
            - "😠 Ärgerlich"
            - "😰 Ängstlich"
            - "😴 Müde"
    reason:
      name: Grund
      description: Grund für die Stimmung
      required: false
      example: "Hat gespielt"
      selector:
        text:

log_medication:
  name: Medikation erfassen
  description: Erfasst verabreichte Medikamente
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    medication_name:
      name: Medikament
      description: Name des Medikaments
      required: true
      example: "Antibiotikum"
      selector:
        text:
    dosage:
      name: Dosierung
      description: Verabreichte Dosierung
      required: false
      example: "1 Tablette"
      selector:
        text:
    time:
      name: Zeitpunkt
      description: Zeitpunkt der Verabreichung
      required: false
      example: "08:00"
      selector:
        time:
    notes:
      name: Notizen
      description: Zusätzliche Notizen
      required: false
      selector:
        text:
          multiline: true

emergency:
  name: Notfallmodus
  description: Aktiviert oder deaktiviert den Notfallmodus
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    activate:
      name: Aktivieren
      description: Notfallmodus aktivieren (true) oder deaktivieren (false)
      required: true
      default: true
      selector:
        boolean:
    reason:
      name: Grund
      description: Grund für den Notfall
      required: false
      example: "Verletzung"
      selector:
        text:
    contact_vet:
      name: Tierarzt kontaktieren
      description: Soll der Tierarzt kontaktiert werden?
      required: false
      default: false
      selector:
        boolean:

reset_data:
  name: Daten zurücksetzen
  description: Setzt Daten des Hundes zurück
  fields:
    dog_name:
      name: Hundename
      description: Name des Hundes
      required: true
      example: "Max"
      selector:
        text:
    confirm:
      name: Bestätigung
      description: Geben Sie 'RESET' ein zur Bestätigung
      required: true
      example: "RESET"
      selector:
        text:
    reset_type:
      name: Reset-Typ
      description: Art des Resets
      required: false
      default: "daily"
      selector:
        select:
          options:
            - "daily"
            - "all"
