
blueprint:
  name: PawControl – Auto Start/Stop GPS Tracking
  domain: automation
  input:
    dog_id:
      name: Hund-ID
      selector: { text: {} }
    start_on_device_tracker_state:
      name: Device Tracker-Entitäten (startet bei 'not_home'→'home' Wechsel)
      default: []
      selector: { entity: { domain: device_tracker, multiple: true } }
trigger:
  - platform: state
    entity_id: !input start_on_device_tracker_state
    from: not_home
    to: home
action:
  - service: pawcontrol.gps_start_walk
    data:
      dog_id: !input dog_id
      walk_type: auto_detected
mode: single
