blueprint:
  name: Paw Control - Feeding Reminder
  description: Send reminders for dog feeding at specified times with snooze functionality
  domain: automation
  source_url: https://github.com/yourusername/pawcontrol/blob/main/blueprints/automation/feeding_reminder.yaml
  input:
    dog_sensor:
      name: Dog Last Feeding Sensor
      description: Select the last feeding sensor for your dog
      selector:
        entity:
          domain: sensor
          integration: pawcontrol
    dog_name:
      name: Dog Name
      description: Name of your dog for the notification
      default: "your dog"
      selector:
        text:
    meal_type:
      name: Meal Type
      description: Which meal is this reminder for?
      default: "dinner"
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
    meal_time:
      name: Meal Time
      description: When should the reminder be sent?
      default: "18:00:00"
      selector:
        time:
    notify_service:
      name: Notification Service
      description: Which notification service to use
      default: notify.mobile_app
      selector:
        text:
    reminder_repeat_minutes:
      name: Reminder Repeat
      description: How often to repeat the reminder (minutes)
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: "min"
    snooze_minutes:
      name: Snooze Duration
      description: How long to snooze when requested (minutes)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          step: 5
          unit_of_measurement: "min"
    quiet_hours_start:
      name: Quiet Hours Start
      description: Don't send reminders before this time
      default: "07:00:00"
      selector:
        time:
    quiet_hours_end:
      name: Quiet Hours End
      description: Don't send reminders after this time
      default: "22:00:00"
      selector:
        time:

trigger:
  - platform: time
    at: !input meal_time
    id: meal_time_trigger
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: SNOOZE_FEEDING
    id: snooze_trigger

condition:
  - condition: time
    after: !input quiet_hours_start
    before: !input quiet_hours_end

action:
  - choose:
      - conditions:
          - condition: trigger
            id: snooze_trigger
        sequence:
          - delay:
              minutes: !input snooze_minutes
          - condition: time
            after: !input quiet_hours_start
            before: !input quiet_hours_end
          - service: !input notify_service
            data:
              title: "🍽️ {{ !input dog_name | title }} - {{ !input meal_type | title }} Reminder"
              message: "Time to feed {{ !input dog_name }}!"
              data:
                tag: "pawcontrol_feeding_{{ !input meal_type }}"
                persistent: true
                actions:
                  - action: "FEED_CONFIRM"
                    title: "Fed ✅"
                  - action: "SNOOZE_FEEDING"
                    title: "Snooze ⏰"
      - conditions:
          - condition: trigger
            id: meal_time_trigger
        sequence:
          - service: !input notify_service
            data:
              title: "🍽️ {{ !input dog_name | title }} - {{ !input meal_type | title }} Time"
              message: "Time for {{ !input dog_name }}'s {{ !input meal_type }}!"
              data:
                tag: "pawcontrol_feeding_{{ !input meal_type }}"
                persistent: true
                importance: high
                actions:
                  - action: "FEED_CONFIRM"
                    title: "Fed ✅"
                  - action: "SNOOZE_FEEDING"
                    title: "Snooze ⏰"
          - repeat:
              count: 3
              sequence:
                - delay:
                    minutes: !input reminder_repeat_minutes
                - condition: time
                  after: !input quiet_hours_start
                  before: !input quiet_hours_end
                - service: !input notify_service
                  data:
                    title: "🍽️ Reminder: {{ !input dog_name | title }} {{ !input meal_type | title }}"
                    message: "{{ !input dog_name }} still needs {{ !input meal_type }}!"
                    data:
                      tag: "pawcontrol_feeding_{{ !input meal_type }}"
                      persistent: true
                      importance: high
                      actions:
                        - action: "FEED_CONFIRM"
                          title: "Fed ✅"
                        - action: "SNOOZE_FEEDING"
                          title: "Snooze ⏰"

mode: restart
