blueprint:
  name: Paw Control - Medication Reminder
  description: Remind to give medication at specified times with confirmation tracking
  domain: automation
  source_url: https://github.com/yourusername/pawcontrol/blob/main/blueprints/automation/medication_reminder.yaml
  input:
    dog_id:
      name: Dog ID
      description: The ID of your dog in Paw Control
      selector:
        text:
    name:
      name: Dog Name
      description: Display name of your dog
      default: "your dog"
      selector:
        text:
    medication_name:
      name: Medication Name
      description: Name of the medication
      selector:
        text:
    medication_dose:
      name: Medication Dose
      description: Dosage information
      default: "1 tablet"
      selector:
        text:
    medication_times:
      name: Medication Times
      description: When to give medication (multiple times allowed)
      selector:
        time:
    notify_service:
      name: Notification Service
      description: Which notification service to use
      default: notify.mobile_app
      selector:
        text:
    reminder_persistent:
      name: Persistent Notification
      description: Keep notification until acknowledged
      default: true
      selector:
        boolean:
    critical_medication:
      name: Critical Medication
      description: Is this critical medication that must not be missed?
      default: false
      selector:
        boolean:
    max_reminders:
      name: Maximum Reminders
      description: How many times to remind if not acknowledged
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
    reminder_interval:
      name: Reminder Interval
      description: Minutes between reminders
      default: 15
      selector:
        number:
          min: 5
          max: 60
          step: 5
          unit_of_measurement: "min"

trigger:
  - platform: time
    at: !input medication_times
    id: medication_time
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: MED_GIVEN
    id: medication_confirmed
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: MED_SNOOZE
    id: medication_snoozed

condition: []

variables:
  is_critical: !input critical_medication
  max_remind: !input max_reminders
  remind_interval: !input reminder_interval

action:
  - choose:
      # Medication time reached
      - conditions:
          - condition: trigger
            id: medication_time
        sequence:
          - service: !input notify_service
            data:
              title: >
                {% if is_critical %}
                🚨 CRITICAL: {{ !input medication_name }}
                {% else %}
                💊 Medication Time: {{ !input medication_name }}
                {% endif %}
              message: "Time to give {{ !input name }} {{ !input medication_dose }} of {{ !input medication_name }}"
              data:
                tag: "pawcontrol_medication_{{ !input dog_id }}_{{ !input medication_name | lower | replace(' ', '_') }}"
                persistent: !input reminder_persistent
                importance: >
                  {% if is_critical %}high{% else %}default{% endif %}
                actions:
                  - action: "MED_GIVEN"
                    title: "Given ✅"
                  - action: "MED_SNOOZE"
                    title: "Snooze 15min ⏰"
          
          # Send reminders if not acknowledged
          - repeat:
              count: !input max_reminders
              sequence:
                - delay:
                    minutes: !input reminder_interval
                - service: !input notify_service
                  data:
                    title: >
                      {% if is_critical %}
                      🚨 URGENT REMINDER: {{ !input medication_name }}
                      {% else %}
                      💊 Reminder: {{ !input medication_name }}
                      {% endif %}
                    message: >
                      {{ !input name }} still needs {{ !input medication_dose }} of {{ !input medication_name }}!
                      {% if repeat.index == max_remind %}
                      This is the final reminder!
                      {% endif %}
                    data:
                      tag: "pawcontrol_medication_{{ !input dog_id }}_{{ !input medication_name | lower | replace(' ', '_') }}"
                      persistent: true
                      importance: high
                      channel: >
                        {% if is_critical %}alarm{% else %}reminder{% endif %}
                      actions:
                        - action: "MED_GIVEN"
                          title: "Given ✅"
                        - action: "MED_SNOOZE"
                          title: "Snooze ⏰"
      
      # Medication confirmed
      - conditions:
          - condition: trigger
            id: medication_confirmed
        sequence:
          - service: pawcontrol.log_medication
            data:
              dog_id: !input dog_id
              medication_name: !input medication_name
              dose: !input medication_dose
          - service: !input notify_service
            data:
              message: "clear_notification"
              data:
                tag: "pawcontrol_medication_{{ !input dog_id }}_{{ !input medication_name | lower | replace(' ', '_') }}"
          - service: !input notify_service
            data:
              title: "✅ Medication Logged"
              message: "{{ !input medication_name }} given to {{ !input name }}"
              data:
                tag: "pawcontrol_medication_confirm_{{ !input dog_id }}"
                timeout: 10
      
      # Medication snoozed
      - conditions:
          - condition: trigger
            id: medication_snoozed
        sequence:
          - service: !input notify_service
            data:
              message: "clear_notification"
              data:
                tag: "pawcontrol_medication_{{ !input dog_id }}_{{ !input medication_name | lower | replace(' ', '_') }}"
          - delay:
              minutes: 15
          - service: !input notify_service
            data:
              title: "💊 Medication Reminder (Snoozed)"
              message: "Time to give {{ !input name }} {{ !input medication_dose }} of {{ !input medication_name }}"
              data:
                tag: "pawcontrol_medication_{{ !input dog_id }}_{{ !input medication_name | lower | replace(' ', '_') }}"
                persistent: true
                importance: high
                actions:
                  - action: "MED_GIVEN"
                    title: "Given ✅"
                  - action: "MED_SNOOZE"
                    title: "Snooze Again ⏰"

mode: parallel
max: 10
