blueprint:
  name: PawControl Resilience Escalation Follow-up
  description: >
    Follow-up automation for PawControl resilience manual events and guard
    escalations. Use this blueprint to notify operators or trigger recovery
    actions when manual guard or breaker events are emitted.
  domain: automation
  input:
    notify_service:
      name: Notification service
      description: Service to call when a follow-up event is raised.
      selector:
        text: {}

trigger:
  - platform: event
    event_type: pawcontrol_manual_event
    id: manual_event
  - platform: event
    event_type: pawcontrol_manual_guard
    id: manual_guard_event
  - platform: event
    event_type: pawcontrol_manual_breaker
    id: manual_breaker_event

action:
  - service: logbook.log
    data:
      name: PawControl
      message: Resilience follow-up triggered.
  - service: "{{ notify_service }}"
    data:
      message: "PawControl resilience follow-up event: {{ trigger.id }}"

mode: single
