name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: |
          pytest -q \
            --cov=custom_components/pawcontrol \
            --cov-report=xml:coverage.xml \
            --cov-branch \
            --junitxml=junit.xml \
            -o junit_family=legacy

      - name: Verify coverage artifacts exist
        run: |
          test -f coverage.xml
          test -f junit.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: junit.xml
          report_type: test_results
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
