codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment: true

ignore:
  - "tests/"
  - "docs/"
  - "scripts/"
