# Codecov configuration for PawControl Integration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
  bot: <codecov-bot> #this is a username for Github/Gitlab/Bitbucket
  continue-on-error: true

  coverage:
    status:
      project:
        default: # default is the status check's name, not default settings
          target: auto
          threshold: 1%
          base: auto
          flags:
            - unit
          paths:
            - custom_components/pawcontrol
          # advanced settings
          branches:
            - main
          if_not_found: success
          if_ci_failed: error #success, failure, error, ignore
          informational: true
          only_pulls: false
      tests: # declare a new status context "tests"
        target: 100% # we always want 100% coverage here
        paths: "tests/" # only include coverage in "tests/" folder
      app: # declare a new status context "app"
        paths: "!tests/" # remove all files in "tests/"
      patch:
        default:
          target: 90%
          threshold: 1%
          base: auto
          branches:
            - main
          if_not_found: success
          if_ci_failed: error
          informational: true
          only_pulls: false
          flags:
            - "unit"
          paths:
            - "src"
    changes: true
  precision: 2
  round: down
  range:
    - 70.0
    - 100.0

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: false

comment:
  layout: "components,header,reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main

github_checks:
    annotations: false

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "**/__pycache__/**"
  - "**/test_*.py"
  - "**/conftest.py"
  - "**/*.md"
  - ^tests/.*
  - ^docs/.*
  - ^scripts/.*

flags:
  unittests:
    paths:
      - custom_components/pawcontrol
    carryforward: false

  integration:
    paths:
      - custom_components/pawcontrol
    carryforward: true

  tests:
    paths:
      - tests/
    carryforward: false

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
        - type: "tests"

cli:
  plugins:
    pycoverage:
      report_type: "json"

# Upload settings
uploads:
  - name: "pawcontrol"
    path: "coverage/coverage.xml"
    flags:
      - unittests
    report_type: "pytest"
