# Codecov configuration for PawControl Integration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
  continue-on-error: true

coverage:
  precision: 2
  round: down
  range:
    - 70.0
    - 100.0

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags:
          - unittests
        paths:
          - custom_components/pawcontrol
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false
    patch:
      default:
        target: 90%
        threshold: 1%
        base: auto
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false
        flags:
          - unittests
        paths:
          - custom_components/pawcontrol

  changes: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: false

comment:
  layout: "components,header,reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main

github_checks:
  annotations: false

# Files to exclude from coverage analysis
ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "**/__pycache__/**"
  - "**/test_*.py"
  - "**/conftest.py"
  - "**/*.md"

# Flag definitions
flags:
  unittests:
    paths:
      - custom_components/pawcontrol
    carryforward: false

  integration:
    paths:
      - custom_components/pawcontrol
    carryforward: true

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: labels
      statuses:
        - type: project
        - type: patch

# Upload settings — coverage.xml is always written to the project root
uploads:
  - name: pawcontrol
    path: coverage.xml
    flags:
      - unittests
    report_type: pytest
