# Codecov configuration for PawControl Integration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
  continue-on-error: true

coverage:
  precision: 2
  round: down
  range:
    - 70.0
    - 100.0

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags:
          - unittests
        paths:
          - custom_components/pawcontrol
        branches:
          - main
        informational: true
        only_pulls: false
    patch:
      default:
        target: 90%
        threshold: 1%
        base: auto
        branches:
          - main
        informational: true
        only_pulls: false
        flags:
          - unittests
        paths:
          - custom_components/pawcontrol

  changes: true

parsers:
  gcov:
    branch_detection: true
      conditional: true
      loop: true
      method: true
      macro: false

comment: true

github_checks:
  annotations: false

# Files to exclude from coverage analysis
ignore:
- ^tests/.*
- ^docs/.*
- ^scripts/.*

# Flag definitions
flags:
  unittests:
    paths:
      - custom_components/pawcontrol
    carryforward: false

  integration:
    paths:
      - custom_components/pawcontrol
    carryforward: true

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: labels
      statuses:
        - type: project
        - type: patch
