# Codecov configuration for PawControl Integration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      default:
        target: 75%
        threshold: 1%
        base: auto
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    patch:
      default:
        target: 70%
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - main

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "**/__pycache__/**"
  - "**/test_*.py"
  - "**/conftest.py"
  - "setup.py"
  - "**/*.md"

flags:
  unittests:
    paths:
      - custom_components/pawcontrol
    carryforward: false

  integration:
    paths:
      - custom_components/pawcontrol
    carryforward: true

github_checks:
  annotations: true

# Upload settings
uploads:
  - name: "pawcontrol"
    path: "./coverage.xml"
    flags:
      - unittests
    report_type: "pytest"
