# Codecov configuration for PawControl Integration
# Reference: https://docs.codecov.com/docs/codecovyml-reference
# Validate: curl -X POST --data-binary @.codecov.yml https://api.codecov.io/validate

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  # FIX: range must be a string "start...end", not a YAML list
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        flags:
          - unittests
        paths:
          - custom_components/pawcontrol/
        branches:
          - main
        informational: true
        only_pulls: false
      app:
        target: auto
        threshold: 1%
        paths:
          - custom_components/pawcontrol/

    patch:
      default:
        target: 90%
        threshold: 1%
        base: auto
        branches:
          - main
        informational: true
        only_pulls: false
        flags:
          - unittests
        paths:
          - custom_components/pawcontrol/

    # FIX: `changes` belongs under coverage.status, not under coverage directly
    changes: false

# FIX: `parsers.gcov` is for C/C++ (GCC gcov tool) and is irrelevant for
# Python projects. pytest-cov/coverage.py produces Cobertura XML which
# Codecov parses correctly by default - no explicit parsers block needed.

comment:
  # FIX: `comment: true` (boolean) is not a valid value; comment is a map.
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

github_checks:
  annotations: false

# Exclude non-integration paths from coverage analysis
ignore:
  - "tests/**"
  - "docs/**"
  - "scripts/**"

# Flag definitions - only define flags that are actually uploaded by CI.
# The CI uploads with `flags: unittests` only.
flags:
  unittests:
    paths:
      - custom_components/pawcontrol/
    carryforward: false

# FIX: Removed `integration` flag (defined but never uploaded by CI → dead entry).
# FIX: Removed `flag_management` with `carryforward_mode: "labels"` - that
# setting requires Codecov ATS (Automated Test Selection) with a separate
# CODECOV_STATIC_TOKEN and codecov/codecov-ats Action, none of which are
# configured. For a single-module HA integration without partial test runs,
# flag_management adds no value and creates misleading dashboard entries.
