name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Create Release Archive
        run: |
          # Create release directory
          mkdir -p release_tmp
          
          # Copy integration files
          cp -r custom_components release_tmp/
          
          # Copy documentation
          cp README.md release_tmp/
          cp info.md release_tmp/
          cp hacs.json release_tmp/
          
          # Create ZIP archive
          cd release_tmp
          zip -r ../paw_control-${VERSION}.zip ./*
          cd ..
          
          # Cleanup
          rm -rf release_tmp
          
          # List created files for verification
          ls -la *.zip
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            paw_control-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## 🐶 Paw Control Release ${GITHUB_REF#refs/tags/}
            
            ### Installation via HACS
            1. Open HACS in Home Assistant
            2. Go to "Integrations"
            3. Click the three dots (⋮) in the top right
            4. Select "Custom repositories"
            5. Add URL: `https://github.com/Bigdaddy1990/paw_control`
            6. Category: "Integration"
            7. Click "Add"
            8. Search for "Paw Control" and install
            9. Restart Home Assistant
            
            ### Manual Installation
            1. Download the `paw_control-*.zip` file
            2. Extract to your Home Assistant `custom_components/` directory
            3. Restart Home Assistant
            4. Add the integration via Settings → Devices & Services
            
            ### What's New
            See the commit history for detailed changes in this release.
            
            ### Support
            - 🐛 Bug Reports: [GitHub Issues](https://github.com/Bigdaddy1990/paw_control/issues)
            - 💡 Feature Requests: [GitHub Discussions](https://github.com/Bigdaddy1990/paw_control/discussions)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
