name: Bug Report
description: File a bug report
labels: ['bug']
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: How can we reproduce the issue?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant log output.
      render: shell
    validations:
      required: false
