name: Feature request
description: Suggest an idea for improving Paw Control
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this feature important?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
