name: Feature Request
description: Suggest an idea for this project
labels: ['enhancement']
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: Motivation
      description: Why is this feature important?
    validations:
      required: false
