# ruff: noqa: F403, F405
"""Typing stub for dynamic utils re-exports."""

from ._legacy import *
from .serialize import (
    serialize_dataclass,
    serialize_datetime,
    serialize_entity_attributes,
    serialize_timedelta,
)

__all__: list[str] = [
    "ConfigurationValidationResult",
    "DeviceRegistryUpdate",
    "ErrorContext",
    "FireEventKeywordArgs",
    "K",
    "Number",
    "P",
    "PawControlDeviceLinkMixin",
    "PortionValidationResult",
    "R",
    "ServiceCallKeywordArgs",
    "T",
    "V",
    "async_call_add_entities",
    "async_call_hass_service_if_available",
    "async_capture_service_guard_results",
    "async_fire_event",
    "async_get_or_create_dog_device_entry",
    "build_error_context",
    "calculate_age_from_months",
    "calculate_bmi_equivalent",
    "calculate_time_until",
    "chunk_list",
    "clamp",
    "convert_units",
    "create_device_info",
    "deep_merge_dicts",
    "ensure_local_datetime",
    "ensure_utc_datetime",
    "extract_numbers",
    "flatten_dict",
    "format_distance",
    "format_duration",
    "format_relative_time",
    "generate_entity_id",
    "generate_unique_id",
    "is_dict_subset",
    "is_number",
    "merge_configurations",
    "normalise_entity_attributes",
    "normalise_json",
    "normalise_json_mapping",
    "normalise_json_value",
    "normalize_value",
    "parse_weight",
    "resolve_default_feeding_amount",
    "retry_on_exception",
    "safe_divide",
    "safe_get_nested",
    "safe_set_nested",
    "sanitize_dog_id",
    "sanitize_microchip_id",
    "serialize_dataclass",
    "serialize_datetime",
    "serialize_entity_attributes",
    "serialize_timedelta",
    "unflatten_dict",
    "validate_configuration_schema",
    "validate_email",
    "validate_portion_size",
    "validate_time_string",
]
