# Additional scan roots for scripts/enforce_shared_session_guard.py
# Paths are relative to the repository root. The guard now auto-discovers
# Python packages (directories containing ``__init__.py``), and these globs
# remain available for non-package helpers such as future services folders.
roots = [
  "custom_components/pawcontrol",
  "custom_components/pawcontrol/services",
  "custom_components/pawcontrol/services/*",
  "custom_components/pawcontrol/services/**"
]
