# .gemini/config.yaml
have_fun: false

code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: 40
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: false

# Build-/Test-Artefakte ignorieren
ignore_patterns:
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"
  - "**/.mypy_cache/**"
  - "**/.ruff_cache/**"
  - "**/.coverage"
  - "**/htmlcov/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.venv/**"
  - "**/coverage.xml"
  - "**/.tox/**"
  - "**/.DS_Store"
