version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ha-test-stack:
        patterns:
          - "pytest"
          - "pytest-*"
          - "pytest-homeassistant*"
          - "ruff*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
