name: HACS validation
on:
  pull_request:
    paths:
      - "custom_components/**"
      - "hacs.json"
  push:
    branches: [ main, master ]
    paths:
      - "custom_components/**"
      - "hacs.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
