name: HACS validation
on:
  pull_request:
    branches: [ "main" ]
 # push:
  #  branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
