name: HACS validation
on:
  #pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
