name: Issue Assistant

on:
  issues:
    types: [opened]

concurrency:
  group: issue-assistant-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  issue-summary:
    name: AI Issue Summary
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Generate AI summary
        id: ai-summary
        uses: actions/ai-inference@v2
        with:
          prompt: |
            Analyze this GitHub issue and provide:
            1. A concise 2-sentence summary
            2. Suggested labels (bug, enhancement, question, etc.)
            3. Estimated complexity (simple, medium, complex)
            
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}
            
            Format your response as:
            **Summary:** [summary]
            **Labels:** [labels]
            **Complexity:** [complexity]
            
      - name: Comment with summary
        if: success()
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "## 🤖 AI Analysis

          ${{ steps.ai-summary.outputs.response }}

          ---
          *This summary was automatically generated to help with issue triage.*"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
