name: HA Maintenance Tasks

on:
  schedule:
    # Täglich um 3:00 UTC - Hassfest validation (HA Standard)
    - cron: '0 3 * * *'
  workflow_dispatch:

concurrency:
  group: maintenance
  cancel-in-progress: false

jobs:
  daily-hassfest:
    name: Daily HA Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Daily Hassfest Validation
        uses: home-assistant/actions/hassfest@master

  # Stale issues management - HA Standard
  stale:
    name: Stale Issues Management
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Stale Issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had 
            activity for 60 days. It will be closed in 7 days if no further activity occurs.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had 
            activity for 30 days. It will be closed in 7 days if no further activity occurs.
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 60
          days-before-close: 7
          days-before-pr-stale: 30
