name: Pre-commit Lite

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write
  id-token: write

concurrency:
  group: pre-commit-lite-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  pre-commit:
    if: "github.actor != 'github-actions[bot]' || github.event.action != 'labeled' || github.event.label.name == 'pre-commit ci run'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          #ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install uv (with cache)
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: gh pr edit ${{ github.event.number }} --remove-label 'pre-commit ci run'
        if: github.event.action == 'labeled' && github.event.label.name == 'pre-commit ci run'
        env:
          GH_TOKEN: ${{ github.token }}
        
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
        
