name: Mark stale issues and PRs
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity."
          stale-pr-message: "This PR has been automatically marked as stale due to inactivity."
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
          exempt-issue-labels: "security,pinned"
          exempt-pr-labels: "security,pinned"
