name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run ha_fix (check only)
        run: |
          python -m pip install --upgrade pip
          python .github/scripts/ha_fix.py --check

      - name: Install test stack
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-homeassistant-custom-component

      - name: Pytest
        env:
          PYTHONPATH: .
        run: |
          pytest -q --cov=custom_components.pawcontrol --cov-report=xml
